accounts/urls.py
from django.urls import path, include
from accounts.views import *
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),  #127.0.0.1:8000/accounts/login/
    path('signup/', views.signup, name='signup'),  # 127.0.0.1:8000/accounts/login/
    path('logout', views.logout, name='logout'),
    # path('accounts/', include('allauth.urls')),
    # path('google/', views.google_login, name='google'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('mypage/', include('mypage.urls')), # mypage/로 접근하면, mypage.urls 파일을 참고해라!
    path('', include('home.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import *

app_name = 'home'

urlpatterns = [
    path('', home, name='home'),
    path('upload', upload_image, name='upload_image'),
    path('result', result, name='result'),
    path('preview', preview, name='preview'),
]

mypage/urls.py
from django.urls import path
from mypage.views import *

app_name = 'mypage'

urlpatterns = [
    path('like', mypage_like, name='like'),
]

accounts/models.py
import uuid

from django.conf import settings
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.db import models


class UserManager(BaseUserManager):
    # username과 password 상속받음
    def create_user(self, email, nickname, password=None):
        if not email:
            raise ValueError("Users Must Have an email address")

        user = self.model(
            email=self.normalize_email(email),
            nickname=nickname,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, nickname, password):
        if password is None:
            raise TypeError("Superusers must have a password.")

        user = self.create_user(email, nickname, password)
        user.is_superuser = True
        user.is_staff = True
        user.is_active = True
        user.save(using=self._db)
        return user


# AbstarctUser을 상속한 모델을 만드는 방법
class User(AbstractUser):
    # id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    username = models.CharField("아이디", max_length=40, default='', unique=True)  # unique default false
    password = models.CharField("비밀번호", max_length=300, null=False)  # 암호화 대비 넉넉하게
    nickname = models.CharField("이름", max_length=40, null=False)
    birth = models.DateField("생일", null=False)
    gender = models.CharField("성별", max_length=20, null=False)
    email = models.EmailField("이메일", max_length=300, null=False)
    first_name = None
    last_name = None
    date_joined = None

    USERNAME_FIELD = 'username'  # for using for login

    # REQUIRED_FIELDS 변수에 추가된 필드를 넣어줘야 추후에 supseruser 생성 시에 해당 데이터도 입력 받음
    # password는 이미 REQUIRED_FIELDS 변수
    REQUIRED_FIELDS = ['email', 'nickname', 'birth', 'gender']

    def __str__(self):
        return self.username

home/models.py
from django.db import models
from accounts.models import User


# Create your models here.

class ImageUpload(models.Model):
    image = models.FileField("이미지", upload_to='images/', null=True, blank=True)
    # null은 DB에 저장될 때 빈 공간을 허용하는 옵션

    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, verbose_name="사용자")

    # 이미지 업로드와 유저의 관계가 foreignkey로 연결
    # on_delete : 사용자가 삭제되면 그 사용자가 올린 것도 모두 지워버릴 것

    # admin 모드일 때 제목으로 파일 구분할 수 있음
    # def __str__(self):
    #     return str(self.filename)

    class Meta:
        db_table = 'imageUpload'
        verbose_name = '이미지 업로드'
        verbose_name_plural = '이미지 업로드'

mypage/models.py
from django.db import models

# Create your models here.

home/forms.py
from django import forms
from .models import ImageUpload


class ImageUploadForm(forms.ModelForm):
    class Meta:
        model = ImageUpload
        fields = ['image', 'user']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import authenticate

# create한 login 함수랑 겹치면 안됨
from django.contrib.auth import login as auth_login

from django.contrib.auth.hashers import make_password

from .models import User


# Create your views here.
def logout(request):
    if request.method == 'POST':
        auth_logout(request)
        print("Logged out successfully")
    return redirect('/')


def login(request):
    if request.method == 'GET':
        return render(request, 'account/login.html')

    elif request.method == 'POST':
        errMsg = {}
        username = request.POST.get('username')
        password = request.POST.get('password')
        print(f"username : {username}, password : {password}")
        user = authenticate(request, username=username, password=password)

        # 로그인 성공
        if user is not None:
            auth_login(request, user)
            print("logged in successfully")
            return redirect('home:home')

        # 로그인 실패
        else:
            errMsg = {"로그인을 실패했습니다."}
            print("login failed")
            return render(request, 'account/login.html', errMsg)


# 회원가입
def signup(request):
    if request.method == 'GET':
        return render(request, 'account/signup.html')

    elif request.method == 'POST':
        # 입력 데이터 user 객체에 저장
        user = User(
            username=request.POST['username'],
            password=make_password(request.POST['password']),
            nickname=request.POST['nickname'],
            birth=request.POST['birth'],
            gender=request.POST['gender'],
            email=request.POST['email'] + "@" + request.POST['email-detail']
        )
        user.save()

        # 회원가입 후, 로그인 진행
        new_user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if new_user is not None:
            auth_login(request, new_user)
            return redirect('home:home')  # 홈으로 이동


def get_redirect_if_exists(request):
    redirect = None
    if request.GET:
        if request.GET.get('next'):
            redirect = str(request.GET.get('next'))
    return redirect


def google_login(request):
    pass
#     client_id = CLIENT_ID
#     return redirect(f"{GOOGLE_REDIRECT}?client_id={client_id}&response_type=code&redirect_uri={GOOGLE_CALLBACK_URI}&scope={scope}")

home/views.py
import os
from uuid import uuid4

from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.http import JsonResponse
from . import models
from .forms import ImageUploadForm
from .models import ImageUpload
# from .caption_generator import generate_caption
# from .song_recommender import recommend_song
from django.urls import reverse


def home(request):
    return render(request, 'home/home.html')


def upload_image(request):
    return render(request, 'home/home.html')


def preview(request):
    if request.method == 'POST':
        form = ImageUploadForm(request.POST, request.FILES)
        if form.is_valid():
            image_instance = form.save(commit=False)  # DB에 바로 저장하지 않음
            # 임시 경로에 이미지를 저장
            response_data = {
                'image_url': image_instance.image.url
            }
            return JsonResponse(response_data)
    return render(request, 'home/home.html')


def save(request):
    if request.method == 'POST':
        form = ImageUploadForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return render(request, 'home/home.html')  # 성공 페이지로 render
    return redirect('failure')  # 실패 페이지로 redirect


def result(request):
    return render(request, 'home/result.html')

mypage/views.py
from django.shortcuts import render, redirect

# Create your views here.
def mypage_like(request):
    return render(request, 'mypage/like.html')

templates/Abase.html
<!DOCTYPE html>
{% block content %}
{% block title %}Imagine : 감성노래 추천 웹서비스{% endblock %}
{% endblock %}
{% load static %}
<html lang="ko">
<head>
    <title>Imagine : 감성노래 추천 웹서비스</title>
    <meta charset="UTF-8">

    <style>
        @import url('https://fonts.googleapis.com/css2?family=Noto+Serif+KR&display=swap');
        .noto-serif-kr-regular {
          font-family: "Noto Serif KR", serif;
          font-weight: 400;
          font-style: normal;
        }

        * {
            background-color:#FDF4C9;
        }
        .title{
            left: 50%;
            transform: translateX(-50%);
            top: 20px;
            position: absolute;
            width: 300px;
            height: 100px;
            color: rgb(94, 130, 35);
            font-family: "Noto Serif KR";
            font-size: 55px;
            font-weight: 700;
            line-height: 100px;
            letter-spacing: 0px;
            text-align: center;
            cursor : pointer
        }
        .menu img{
            position: absolute;
            top: 30px;
            left: 30px;
            width: 45px;
            cursor : pointer
        }
    </style>

{% block script %}
{% endblock %}

{% block style %}
{% endblock %}

</head>
<body>
{% if user.is_authenticated %}
<div class="menu">
    <a href="{% url 'mypage:like' %}">
        <img src="{% static 'image/menu-icon.png' %}" alt="menu">
    </a>
</div>
{% endif %}
<div>
    <a href="{% url 'home:home' %}">
        <h1 class="title">Imagine</h1>
    </a>
</div>

<ul>
    <li><a href="{% url 'account:login' %}">Login</a></li>
    {% if user.is_authenticated %}
    <li><a href="{% url 'account:signup' %}">Sign up</a></li>
    {% endif %}
</ul>
{% block content %}{% endblock %}
</body>

</html>

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Imagine : 감성노래 추천 웹서비스{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Serif+KR&display=swap" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script> <!-- jQuery 라이브러리 추가 -->

    <style>
        body {
            background-color: #FDF4C9;
            margin: 0;
            padding: 0;
            font-family: "Noto Serif KR", serif;
        }

        .header {
            display: flex;
            flex-direction: column;
            align-items: center;
            padding: 20px;
            font-size: 55px;
            font-weight: 700;
            color: rgb(94, 130, 35);
            position: absolute;
            width: 100%;
            top: 0;
            left: 0;
            background: none;
            box-sizing: border-box;
        }

        .header a {
            text-decoration: none;
            color: inherit;
        }

        .menu, .logo, .nav-links {
            display: flex;
            align-items: center;
        }

        .menu {
            position: absolute;
            top: 20px;
            left: 20px;
            gap: 20px;
            font-size: 18px;
            font-weight: 400;
        }

        .logo {
            position: absolute;
            top: 78px;
            left: 50%;
            transform: translateX(-50%);
        }

        .nav-links {
            position: absolute;
            top: 20px;
            right: 20px;
            gap: 20px;
            font-size: 18px;
            font-weight: 400;
        }

        .main-container {
            display: flex;
            flex-direction: column;
            align-items: center;
            width: 100%;
            padding-top: 150px;
            box-sizing: border-box;
        }
    </style>

    <!--자식 style 템플릿에 들어갈 부분-->
    {% block style %}
    {% endblock %}

</head>


<body>

<div class="header">

    <div class="menu">
        <a href="{% url 'mypage:like' %}">Menu</a>
    </div>
    <div class="logo">
        <a href="{% url 'home:home' %}">Imagine</a>
    </div>
    <div class="nav-links">
        {% if request.user.is_authenticated %}
            <a href={% url 'accounts:logout' %} id="logout-link">Logout</a>
            <!--로그아웃 요청은 POST 요청 <a>는 GET 요청이므로 JS를 이용하여 POST 요청-->
            <form id="logout-form" method="post" action="{% url 'accounts:logout' %}" style="display:none;">
                {% csrf_token %}
            </form>
        {% else %}
            <a href="{% url 'accounts:login' %}">Login</a>
            <a href="{% url 'accounts:signup' %}">Sign up</a>
        {% endif %}
    </div>
</div>

<!--자식 content 템플릿에 들어갈 부분-->
{% block content %}
{% endblock %}

{#    logout POST 요청#}
<script>
    document.getElementById('logout-link').addEventListener('click', function (event) {
        event.preventDefault();
        document.getElementById('logout-form').submit();
    });
</script>

</body>
</html>

templates/home/Ahome.html
{% extends 'base.html' %}

{% block script %}
<!--js 관련 코드(자바스크립트) 작성-->
{% endblock %}

{% load static %}
<!--static에 해당하는 코드 작성 (css파일 연결)-->

{% block style %}
<style>
    .img-box {
        display: flex;
        left: 50%;
        transform: translateX(-50%);
        top: 160px;
        position: relative;
        width: 350px;
        height: 320px;
        background: rgb(254, 254, 254);
        border: 3px solid rgb(94, 130, 35);
        border-radius: 40px;
        box-sizing: border-box;
        justify-content: center;
        align-items: center;
    }
    .upload-box {
        display: flex;
        left: 50%;
        transform: translateX(-50%);
        top: 520px;
        position: absolute;
        width: 630px;
        height: 50px;
        align-items: center;
        background: rgb(254, 254, 254);
        border: 3px solid rgb(94, 130, 35);
        border-radius: 40px;
        box-sizing: border-box;
        z-index: 1;
    }
    .upload-title {
        margin-right: auto;
        width: 550px;
        margin-left: 20px;
        background: rgb(254, 254, 254);
        color: rgb(0, 0, 0);
        font-family: "Noto Serif KR";
        font-size: 22px;
        font-weight: 500;
        text-align: left;
    }
    .upload-button {
        margin-left: auto;
        width: 20%;
        margin-right: 20px;
        background: rgb(254, 254, 254);
        color: rgb(94, 130, 35);
        font-family: "Noto Serif KR";
        font-size: 22px;
        font-weight: 700;
        text-align: right;
        cursor : pointer
    }
    .enter-button {
        position: absolute;
        top: 620px;
        left: 50%;
        transform: translateX(-50%);
        color: rgb(94, 130, 35);
        font-family: "Noto Serif KR";
        font-size: 22px;
        font-weight: 700;
        text-align: center;
        cursor : pointer
    }
</style>
{% endblock %}

<!--html 코드 작성-->
{% block content %}

<div class="">

</div>

<div class="img-box">
    <img class="img-upload" src="{% static 'image/christmas.png' %}" alt="menu" width="250">
</div>

<div class="upload-box">
    <div class="upload-title">
        IMG_3666.JPG
    </div>
    <div class="upload-button">
        Upload
    </div>
</div>
<div class="enter-button">
    Enter
</div>
{% endblock %}

<!--깃허브 연동 테스트-->

templates/home/exp.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

</body>
</html>

templates/home/home.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    <style>
        .img-box {
            display: flex;
            left: 50%;
            transform: translateX(-50%);
            top: 200px;
            position: relative;
            width: 350px;
            height: 320px;
            background: rgb(254, 254, 254);
            border: 3px solid rgb(94, 130, 35);
            border-radius: 40px;
            box-sizing: border-box;
            justify-content: center;
            align-items: center;
        }

        .upload-box {
            display: flex;
            margin: 0 auto;
            left: 50%;
            transform: translateX(-50%);
            top: 575px;
            position: absolute;
            width: 100%;
            max-width: 600px;
            height: 50px;
            align-items: center;
            background: rgb(254, 254, 254);
            border: 3px solid rgb(94, 130, 35);
            border-radius: 40px;
            box-sizing: border-box;
            z-index: 1;
        }

        .upload-title {
            flex-grow: 1;
            margin-left: 20px;
        }

        .upload-title .upload-name {
            font-family: "Noto Serif KR";
            font-size: 20px;
            color: #333;
            border: none;
        }

        .upload-button {
            background: none;
            display: flex;
            align-items: center;
        }

        .upload-button label {
            margin-left: auto;
            width: auto;
            margin-right: 20px;
            padding: 0;
            font-family: "Noto Serif KR";
            font-size: 20px;
            font-weight: 700;
            color: rgb(94, 130, 35);
            border: none;
            background: none;
            cursor: pointer;
        }

        .enter-button {
            position: absolute;
            top: 670px;
            left: 50%;
            transform: translateX(-50%);
            text-align: center;
            cursor: pointer
        }

        .enter-button a {
            color: rgb(94, 130, 35);
            font-family: "Noto Serif KR";
            font-size: 22px;
            font-weight: 700;
            text-decoration: none;
        }
    </style>

{% endblock %}

{% block content %}
    <script>

        // 이미지 파일명 & 미리보기
        function imageView(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    // 이미지 가져오기
                    $('.tempImage').attr('src', e.target.result)

                    // 파일명 가져오기
                    document.querySelector('.upload-name').value = input.files[0].name;
                }

                reader.readAsDataURL(input.files[0]);
            }
        }


    </script>

    <!--이미지 업로드 박스-->
    <div class="img-box">
        <img class="tempImage" style="max-width: 280px;max-height: 280px;" src=""/>
    </div>

    <!--이미지 파일명 박스-->
    <div class="upload-box">
        {% if request.user.is_authenticated %}
            <div class="upload-title">
                <input class="upload-name" readonly>
            </div>
            <form id="uploadForm" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="upload-button">
                    <label for="inputFile">Upload</label>
                    <input id="inputFile" type="file" class="tempImage" accept="image/*" onchange="imageView(this)"
                           style="display: none;">
                </div>
            </form>
        {% endif %}
    </div>

    <!--엔터 버튼-->
    {% if request.user.is_authenticated %}
        <div class="enter-button">
            <a href="{% url 'home:result' %}">Enter</a>
        </div>
    {% endif %}

{% endblock %}

templates/home/result.html
{% extends 'base.html' %}

{% load static %}

{% block style %}
    <style>
        .container {
            position: absolute;
            top: 150px;
            left: 50%;
            transform: translateX(-50%);
            display: flex;
            flex-direction: column;
            align-items: center;
            width: 100%;
        }

        .image-section {
            margin: 40px 0;
            width: 350px;
            height: 320px;
            background: rgb(254, 254, 254);
            border: 3px solid rgb(94, 130, 35);
            border-radius: 40px;
            box-sizing: border-box;
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .description {
            background-color: #fff;
            border: 3px solid #5e8223;
            border-radius: 40px;
            display: inline-block;
            padding: 15px 30px;
            font-size: 18px;
            margin-bottom: 30px;
            width: 80%; /* width를 100%로 설정하여 부모 컨테이너의 너비에 맞춤 */
            max-width: 700px; /* 최대 너비를 700px로 설정 */
            height: 50px; /* 높이를 300px로 고정 */
            overflow-y: auto; /* 내용이 넘칠 경우 스크롤 생성 */
        }

        /* 스크롤바 스타일 추가 */
        .description::-webkit-scrollbar {
            width: 12px;
        }

        .description::-webkit-scrollbar-thumb {
            background-color: #5e8223;
            border-radius: 20px;
            border: 2px solid #fff;
        }

        .description::-webkit-scrollbar-track {
            background: #f1f1f1;
            border-radius: 20px;
            border: 1px solid #ddd;
        }

        .music-list {
            display: flex;
            flex-direction: column;
            align-items: center;
            width: 100%;
        }

        .music-item {
            display: flex;
            align-items: center;
            width: 90%;
            max-width: 700px;
            background-color: #fff;
            border: 3px solid #5e8223;
            border-radius: 40px;
            margin-bottom: 15px;
            padding: 10px;
        }

        .music-image {
            width: 50px;
            height: 50px;
            border-radius: 50%;
            margin-right: 20px;
        }

        .music-info {
            flex-grow: 1;
            text-align: left;
            font-size: 18px;
            color: #5e8223;
        }

        .music-actions {
            display: flex;
            align-items: center;
        }

        .play-button,
        .favorite-button {
            font-size: 24px;
            background: none;
            border: none;
            cursor: pointer;
            color: #5e8223;
            margin-left: 10px;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="image-section">
            <img class="img-upload" src="{% static 'images/christmas.png' %}" alt="menu" width="250">
        </div>
        <div class="description">
            <p>Harmony of trees and lights, green and red is wonderful. It's full of Christmas mood.</p>
        </div>
        <div class="music-list">
            <div class="music-item">
                <img class="music-image" src="{% static 'images/mariah_carey.png' %}" alt="Mariah Carey">
                <div class="music-info">
                    <p>Mariah Carey - All I Want for Christmas Is You</p>
                </div>
                <div class="music-actions">
                    <button class="play-button">&#9658;</button>
                    <button class="favorite-button">&#9733;</button>
                </div>
            </div>
            <div class="music-item">
                <img class="music-image" src="{% static 'images/ariana_grande.png' %}" alt="Ariana Grande">
                <div class="music-info">
                    <p>Ariana Grande - Last Christmas</p>
                </div>
                <div class="music-actions">
                    <button class="play-button">&#9658;</button>
                    <button class="favorite-button">&#9733;</button>
                </div>
            </div>
            <div class="music-item">
                <img class="music-image" src="{% static 'images/kelly_clarkson.png' %}" alt="Kelly Clarkson">
                <div class="music-info">
                    <p>Kelly Clarkson - Underneath the Tree</p>
                </div>
                <div class="music-actions">
                    <button class="play-button">&#9658;</button>
                    <button class="favorite-button">&#9733;</button>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/home/upload.html
{% extends 'base.html' %}

{% block script %}

{% endblock %}

{% load static %}

{% block style %}

    <style>
        /* 숨겨진 파일 입력 필드 */
        #file-input {
            display: none;
        }

        .img-box {
            display: flex;
            left: 50%;
            transform: translateX(-50%);
            top: 200px;
            position: relative;
            width: 350px;
            height: 320px;
            background: rgb(254, 254, 254);
            border: 3px solid rgb(94, 130, 35);
            border-radius: 40px;
            box-sizing: border-box;
            justify-content: center;
            align-items: center;
        }

        .upload-box {
            display: flex;
            margin: 0 auto;
            left: 50%;
            transform: translateX(-50%);
            top: 575px;
            position: absolute;
            width: 100%;
            max-width: 600px;
            height: 50px;
            align-items: center;
            background: rgb(254, 254, 254);
            border: 3px solid rgb(94, 130, 35);
            border-radius: 40px;
            box-sizing: border-box;
            z-index: 1;
        }

        .upload-title {
            flex-grow: 1;
            font-family: "Noto Serif KR";
            font-size: 20px;
            color: #333;
            margin-left: 20px;
        }

        .upload-button {
            background: none;
            display: flex;
            align-items: center;
        }

        .upload-button button {
            margin-left: auto;
            width: auto;
            margin-right: 20px;
            padding: 0;
            font-family: "Noto Serif KR";
            font-size: 20px;
            font-weight: 700;
            color: rgb(94, 130, 35);
            border: none;
            background: none;
            cursor: pointer;
        }

        .enter-button {
            position: absolute;
            top: 670px;
            left: 50%;
            transform: translateX(-50%);
            text-align: center;
            cursor: pointer
        }

        .enter-button a {
            color: rgb(94, 130, 35);
            font-family: "Noto Serif KR";
            font-size: 22px;
            font-weight: 700;
            text-decoration: none;
        }
    </style>
{% endblock %}
{% block content %}
    <!--이미지 업로드 박스-->
    <div class="img-box">
        <img src="{{ home.image.url }}">
    </div>

    <!--이미지 파일명 박스-->
    <div class="upload-box">
        {% if request.user.is_authenticated %}
            <div class="upload-title">
            </div>
            <form method="POST" action="{% url 'upload' %}" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="upload-button">
                    <button type="submit">Upload</button>
                    <input type="file" id="file-input">
                </div>
            </form>
        {% endif %}
    </div>

    <script>
        // JavaScript를 사용하여 파일 입력 필드를 감추고 버튼 클릭 시 파일 선택 창을 열도록 설정
        document.querySelector('.upload-button').addEventListener('click', function () {
            document.getElementById('file-input').click();
        });
    </script>

    <!--엔터 버튼-->
    {% if request.user.is_authenticated %}
        <div class="enter-button">
            <a href="{% url 'home:result' %}">Enter</a>
        </div>
    {% endif %}

{% endblock %}